services:
  shopapi:
    build:
      dockerfile: Dockerfile
    container_name: shopapi-container
    ports:
      - "8085:8085"  
    environment:
      SPRING_PROFILES_ACTIVE: prod 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/shopapi
      SPRING_DATASOURCE_USERNAME: shopapi
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DDL_AUTO: validate
    depends_on:
      - db
    networks:
      - shopapi-network

  db:
    image: mysql:latest
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: shopapi
      MYSQL_USER: shopapi
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - shopapi-network
    command:
      --bind-address=0.0.0.0
  
volumes:
  mysql-data:

networks:
  shopapi-network:
    driver: bridge
