spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        dialect: 
        
  data:
    mongodb:
      uri: ${SPRING_MONGODB_URI:mongodb://localhost:27017/musicapi}
